# Generated by Django 2.0.13 on 2019-04-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190428_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='titulo',
            new_name='nome',
        ),
    ]
