# Generated by Django 2.0.13 on 2019-04-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190428_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='nome',
            new_name='titulo',
        ),
    ]
