# Generated by Django 2.0.13 on 2019-04-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190428_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='titulo',
        ),
    ]
