# Generated by Django 2.0.13 on 2019-04-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190428_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='titulo',
            new_name='nome',
        ),
    ]
