# Generated by Django 2.0.13 on 2019-04-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_livro_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='picture',
        ),
    ]
