# Generated by Django 2.0.13 on 2019-04-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_livro_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/pictures/%Y/%m/%d/'),
        ),
    ]
