# Generated by Django 2.0.13 on 2019-04-28 23:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190428_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Ficcao', 'Ficcao'), ('Acao', 'Acao')], default='Drama', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rent',
            name='data_devolucao',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 23, 57, 12, 561286, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='data_rent',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 23, 57, 12, 561256, tzinfo=utc)),
        ),
    ]
