# Generated by Django 2.0.13 on 2019-04-29 00:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20190428_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Ficcao', 'Ficcao'), ('Ação', 'Ação'), ('Romance', 'Romance'), ('Cronica', 'Crônica'), ('Poesia ', 'Poesia '), ('Aventura', 'Aventura'), ('Infantil', 'Infantil')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rent',
            name='data_devolucao',
            field=models.DateField(default=datetime.datetime(2019, 4, 29, 0, 6, 8, 885772, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='data_rent',
            field=models.DateField(default=datetime.datetime(2019, 4, 29, 0, 6, 8, 885744, tzinfo=utc)),
        ),
    ]
