# Generated by Django 2.0.13 on 2019-04-29 02:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20190428_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='venda',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rent',
            name='data_devolucao',
            field=models.DateField(default=datetime.datetime(2019, 4, 29, 2, 26, 24, 587313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='data_rent',
            field=models.DateField(default=datetime.datetime(2019, 4, 29, 2, 26, 24, 587284, tzinfo=utc)),
        ),
    ]
