# Generated by Django 2.0.13 on 2019-04-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20190428_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='data_devolucao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='data_rent',
            field=models.DateField(),
        ),
    ]
