# Generated by Django 2.0.13 on 2019-06-20 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0020_auto_20190610_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aluguel', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Livro')),
            ],
        ),
        migrations.RemoveField(
            model_name='rent',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='livro',
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
