# Generated by Django 2.0.13 on 2019-06-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20190620_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='tipo',
            field=models.CharField(default='Alugado', max_length=50),
        ),
    ]
