# Generated by Django 2.0.13 on 2019-06-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_aluguel_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.ManyToManyField(related_name='livros', to='web.Livro')),
            ],
        ),
    ]
