# Generated by Django 2.0.13 on 2019-06-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='organization',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
