# Generated by Django 2.0.13 on 2019-06-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_carrinho_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='organization',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='status',
            field=models.CharField(default='Espera', max_length=50),
        ),
    ]
