# Generated by Django 2.0.13 on 2019-06-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_carrinho_pendencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='livro',
        ),
    ]
