# Generated by Django 2.0.13 on 2019-06-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_remove_carrinho_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='livro',
            field=models.ManyToManyField(related_name='livros', to='web.Livro'),
        ),
    ]
