# Generated by Django 2.0.13 on 2019-06-25 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_carrinho_livro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='livro',
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
    ]
