# Generated by Django 2.0.13 on 2019-06-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20190625_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrinhoAluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Espera', max_length=50)),
                ('pendencia', models.BooleanField(default=True)),
                ('livro', models.ManyToManyField(related_name='livros', to='web.Livro')),
            ],
        ),
    ]
