# Generated by Django 2.0.13 on 2019-06-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_carrinhoaluguel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinhoaluguel',
            name='livro',
        ),
        migrations.DeleteModel(
            name='CarrinhoAluguel',
        ),
    ]
