# Generated by Django 2.0.13 on 2019-07-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
